CREATE DATABASE IF NOT EXISTS cse3100_project;

USE cse3100_project;

CREATE TABLE
  users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );